### ISSUE TITLE
关于@EnableJpaRepositories的basePackages问题

### ISSUE THREAD

**Issue by sdut406** [FJiayang/SpringBoot-Two-DataSources-Demo#1]
你好，能请教个问题吗？ 在配置所数据源的时候如果在注解@EnableJpaRepositories里不写basePackages，还有什么办法能发现Repository？ 我在一个项目框架里发现框架里就没有写basePackages之类的代码能运行成功，我在自己的代码里不写就会报Field systemDao in com.xing.spring.springDataJpa.controller.SpringDataJpaController required a bean of type 'com.xing.spring.springDataJpa.dao.system.SystemRepository' that could not be found. 找不到Repository。

**Comment by FJiayang** [comment]
检查一下框架是否做了默认装配的包装，或者定义在外部化配置中
